title: YOGAE
repository: yogae/yogae.github.io
description: "TODO: FIXME:"
show_downloads: true
collections:
  authors:
    output: true
  categories:
    output: true
theme: jekyll-theme-slate
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"